# Generated by Django 5.2 on 2025-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookreserve", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreserve",
            name="publication_date",
            field=models.DateField(null=True, verbose_name="出版日"),
        ),
    ]
