# Generated by Django 5.2 on 2025-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookreserve", "0002_bookreserve_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreserve",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="bookreserve",
            name="reserver",
            field=models.CharField(blank=True, max_length=30, verbose_name="予約者"),
        ),
        migrations.AlterField(
            model_name="bookreserve",
            name="return_date",
            field=models.DateField(blank=True, null=True, verbose_name="返却日"),
        ),
    ]
