# Generated by Django 5.2 on 2025-06-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "bookreserve",
            "0003_alter_bookreserve_picture_alter_bookreserve_reserver_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookreserve",
            name="description",
        ),
        migrations.AlterField(
            model_name="bookreserve",
            name="author",
            field=models.CharField(max_length=60, verbose_name="著者"),
        ),
        migrations.AlterField(
            model_name="bookreserve",
            name="title",
            field=models.CharField(max_length=60, verbose_name="書籍名"),
        ),
    ]
