# Generated by Django 5.2 on 2025-07-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookreserve", "0004_remove_bookreserve_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreserve",
            name="reserver",
            field=models.CharField(
                blank=True, default="-", max_length=30, verbose_name="予約者"
            ),
        ),
    ]
