# Generated by Django 5.2 on 2025-08-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookreserve", "0005_alter_bookreserve_reserver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreserve",
            name="reserver",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="予約者"
            ),
        ),
    ]
