# Generated by Django 5.2 on 2025-10-30 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookreserve", "0006_alter_bookreserve_reserver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="書籍タイトル")),
                ("author", models.CharField(max_length=100, verbose_name="著者名")),
                ("url", models.URLField(blank=True, null=True, verbose_name="商品URL")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "処理中"),
                            ("Approved", "承認済み"),
                            ("Rejected", "却下"),
                        ],
                        default="Pending",
                        max_length=10,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="リクエスト日時"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="リクエスト者",
                    ),
                ),
            ],
            options={
                "verbose_name": "書籍リクエスト",
                "verbose_name_plural": "書籍リクエスト",
                "ordering": ["-requested_at"],
            },
        ),
    ]
